### ISSUE TITLE
[SCAN] sub-01_ses-001

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/bids_template#5]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker
- [X] game controller

### general notes

test general notes

### task-mariostars_run-01 completion

- [ ] series was completed.

### task-mariostars_run-02 completion

- [X] series was completed.

### task-mariostars_run-02 issues

sleep

### task-mariostars_run-03 completion

- [X] series was completed.

### task-mariostars_run-04 completion

- [X] series was completed.

### task-mariostars_run-05 completion

- [ ] series was completed.
